### ISSUE TITLE
供电使用

### ISSUE THREAD

**Issue by forplane** [zhou-you/RxAudio#2]
想问下，耳机孔插入一个外接设备感应器后，这个外界设备通过磁铁产生磁场，然后磁场对感应器产生电阻变化，之后产生电流变化。我是做这个的。
但是在使用供电模块的时候，不知道该怎么来正确使用。

**Comment by zhou-you** [comment]
供电模块其实很简单啊，发出特定频率的振幅达到 1.x几V的电压，从而驱动设备的使能，使设备开始供电。并不是真正的手机给设备供电。
